// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/limits/proto/limits.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CheckLimitsRequest struct {
	Tenant  string            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Streams []*StreamMetadata `protobuf:"bytes,2,rep,name=streams,proto3" json:"streams,omitempty"`
}

func (m *CheckLimitsRequest) Reset()      { *m = CheckLimitsRequest{} }
func (*CheckLimitsRequest) ProtoMessage() {}
func (*CheckLimitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaed9e7d5298ac0f, []int{0}
}
func (m *CheckLimitsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CheckLimitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CheckLimitsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CheckLimitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLimitsRequest.Merge(m, src)
}
func (m *CheckLimitsRequest) XXX_Size() int {
	return m.Size()
}
func (m *CheckLimitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLimitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLimitsRequest proto.InternalMessageInfo

func (m *CheckLimitsRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *CheckLimitsRequest) GetStreams() []*StreamMetadata {
	if m != nil {
		return m.Streams
	}
	return nil
}

type CheckLimitsResponse struct {
	Results []*CheckLimitsResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (m *CheckLimitsResponse) Reset()      { *m = CheckLimitsResponse{} }
func (*CheckLimitsResponse) ProtoMessage() {}
func (*CheckLimitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaed9e7d5298ac0f, []int{1}
}
func (m *CheckLimitsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CheckLimitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CheckLimitsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CheckLimitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLimitsResponse.Merge(m, src)
}
func (m *CheckLimitsResponse) XXX_Size() int {
	return m.Size()
}
func (m *CheckLimitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLimitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLimitsResponse proto.InternalMessageInfo

func (m *CheckLimitsResponse) GetResults() []*CheckLimitsResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type CheckLimitsResult struct {
	StreamHash uint64 `protobuf:"varint,1,opt,name=streamHash,proto3" json:"streamHash,omitempty"`
	Reason     uint32 `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *CheckLimitsResult) Reset()      { *m = CheckLimitsResult{} }
func (*CheckLimitsResult) ProtoMessage() {}
func (*CheckLimitsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaed9e7d5298ac0f, []int{2}
}
func (m *CheckLimitsResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CheckLimitsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CheckLimitsResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CheckLimitsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLimitsResult.Merge(m, src)
}
func (m *CheckLimitsResult) XXX_Size() int {
	return m.Size()
}
func (m *CheckLimitsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLimitsResult.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLimitsResult proto.InternalMessageInfo

func (m *CheckLimitsResult) GetStreamHash() uint64 {
	if m != nil {
		return m.StreamHash
	}
	return 0
}

func (m *CheckLimitsResult) GetReason() uint32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

type GetAssignedPartitionsRequest struct {
}

func (m *GetAssignedPartitionsRequest) Reset()      { *m = GetAssignedPartitionsRequest{} }
func (*GetAssignedPartitionsRequest) ProtoMessage() {}
func (*GetAssignedPartitionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaed9e7d5298ac0f, []int{3}
}
func (m *GetAssignedPartitionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAssignedPartitionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAssignedPartitionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAssignedPartitionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssignedPartitionsRequest.Merge(m, src)
}
func (m *GetAssignedPartitionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetAssignedPartitionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssignedPartitionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssignedPartitionsRequest proto.InternalMessageInfo

type GetAssignedPartitionsResponse struct {
	AssignedPartitions map[int32]int64 `protobuf:"bytes,1,rep,name=assignedPartitions,proto3" json:"assignedPartitions,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (m *GetAssignedPartitionsResponse) Reset()      { *m = GetAssignedPartitionsResponse{} }
func (*GetAssignedPartitionsResponse) ProtoMessage() {}
func (*GetAssignedPartitionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaed9e7d5298ac0f, []int{4}
}
func (m *GetAssignedPartitionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAssignedPartitionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAssignedPartitionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAssignedPartitionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssignedPartitionsResponse.Merge(m, src)
}
func (m *GetAssignedPartitionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetAssignedPartitionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssignedPartitionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssignedPartitionsResponse proto.InternalMessageInfo

func (m *GetAssignedPartitionsResponse) GetAssignedPartitions() map[int32]int64 {
	if m != nil {
		return m.AssignedPartitions
	}
	return nil
}

type StreamMetadata struct {
	StreamHash uint64 `protobuf:"varint,1,opt,name=streamHash,proto3" json:"streamHash,omitempty"`
	TotalSize  uint64 `protobuf:"varint,2,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
}

func (m *StreamMetadata) Reset()      { *m = StreamMetadata{} }
func (*StreamMetadata) ProtoMessage() {}
func (*StreamMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaed9e7d5298ac0f, []int{5}
}
func (m *StreamMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StreamMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StreamMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StreamMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMetadata.Merge(m, src)
}
func (m *StreamMetadata) XXX_Size() int {
	return m.Size()
}
func (m *StreamMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMetadata proto.InternalMessageInfo

func (m *StreamMetadata) GetStreamHash() uint64 {
	if m != nil {
		return m.StreamHash
	}
	return 0
}

func (m *StreamMetadata) GetTotalSize() uint64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

type StreamMetadataRecord struct {
	Zone     string          `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Tenant   string          `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Metadata *StreamMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *StreamMetadataRecord) Reset()      { *m = StreamMetadataRecord{} }
func (*StreamMetadataRecord) ProtoMessage() {}
func (*StreamMetadataRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaed9e7d5298ac0f, []int{6}
}
func (m *StreamMetadataRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StreamMetadataRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StreamMetadataRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StreamMetadataRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMetadataRecord.Merge(m, src)
}
func (m *StreamMetadataRecord) XXX_Size() int {
	return m.Size()
}
func (m *StreamMetadataRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMetadataRecord.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMetadataRecord proto.InternalMessageInfo

func (m *StreamMetadataRecord) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *StreamMetadataRecord) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *StreamMetadataRecord) GetMetadata() *StreamMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*CheckLimitsRequest)(nil), "proto.CheckLimitsRequest")
	proto.RegisterType((*CheckLimitsResponse)(nil), "proto.CheckLimitsResponse")
	proto.RegisterType((*CheckLimitsResult)(nil), "proto.CheckLimitsResult")
	proto.RegisterType((*GetAssignedPartitionsRequest)(nil), "proto.GetAssignedPartitionsRequest")
	proto.RegisterType((*GetAssignedPartitionsResponse)(nil), "proto.GetAssignedPartitionsResponse")
	proto.RegisterMapType((map[int32]int64)(nil), "proto.GetAssignedPartitionsResponse.AssignedPartitionsEntry")
	proto.RegisterType((*StreamMetadata)(nil), "proto.StreamMetadata")
	proto.RegisterType((*StreamMetadataRecord)(nil), "proto.StreamMetadataRecord")
}

func init() { proto.RegisterFile("pkg/limits/proto/limits.proto", fileDescriptor_aaed9e7d5298ac0f) }

var fileDescriptor_aaed9e7d5298ac0f = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcb, 0x6e, 0x13, 0x31,
	0x14, 0x86, 0xc7, 0xb9, 0xb4, 0xf4, 0x14, 0x10, 0x98, 0x14, 0x86, 0xa8, 0xb5, 0x22, 0xc3, 0x22,
	0xab, 0x44, 0x04, 0x16, 0x08, 0xb1, 0x01, 0xd4, 0x42, 0xc5, 0x45, 0xc8, 0x5d, 0x83, 0x64, 0x3a,
	0x56, 0x3a, 0xca, 0xc4, 0x0e, 0xe3, 0x33, 0x48, 0xed, 0x8a, 0x47, 0xe0, 0x31, 0x78, 0x08, 0x1e,
	0x80, 0x65, 0x16, 0x2c, 0xba, 0x24, 0x93, 0x0d, 0xcb, 0x3e, 0x02, 0xaa, 0xc7, 0x81, 0x84, 0x5c,
	0x60, 0xc1, 0x2a, 0x3e, 0xe7, 0xfc, 0xf9, 0x3d, 0xbf, 0xcf, 0x07, 0x3b, 0x83, 0x5e, 0xb7, 0x9d,
	0xc4, 0xfd, 0x18, 0x6d, 0x7b, 0x90, 0x1a, 0x34, 0xbe, 0x68, 0xb9, 0x82, 0x56, 0xdd, 0x0f, 0x7f,
	0x03, 0xf4, 0xc9, 0x91, 0x3a, 0xec, 0xbd, 0x70, 0x33, 0xa1, 0xde, 0x67, 0xca, 0x22, 0xbd, 0x0e,
	0x6b, 0xa8, 0xb4, 0xd4, 0x18, 0x92, 0x06, 0x69, 0x6e, 0x08, 0x5f, 0xd1, 0x36, 0xac, 0x5b, 0x4c,
	0x95, 0xec, 0xdb, 0xb0, 0xd4, 0x28, 0x37, 0x37, 0x3b, 0x5b, 0x85, 0x5b, 0xeb, 0xc0, 0x75, 0x5f,
	0x2a, 0x94, 0x91, 0x44, 0x29, 0x26, 0x2a, 0xbe, 0x0f, 0xd7, 0x66, 0xec, 0xed, 0xc0, 0x68, 0xab,
	0x68, 0x07, 0xd6, 0x53, 0x65, 0xb3, 0x04, 0x6d, 0x48, 0x9c, 0x4f, 0xe8, 0x7d, 0x66, 0xc5, 0x59,
	0x82, 0x62, 0x22, 0xe4, 0xcf, 0xe1, 0xea, 0xdc, 0x94, 0x32, 0x80, 0xe2, 0xaa, 0x67, 0xd2, 0x1e,
	0xb9, 0x8f, 0xad, 0x88, 0xa9, 0xce, 0x79, 0x90, 0x54, 0x49, 0x6b, 0x74, 0x58, 0x6a, 0x90, 0xe6,
	0x25, 0xe1, 0x2b, 0xce, 0x60, 0xfb, 0xa9, 0xc2, 0x47, 0xd6, 0xc6, 0x5d, 0xad, 0xa2, 0xd7, 0x32,
	0xc5, 0x18, 0x63, 0xa3, 0x27, 0x0f, 0xc0, 0xbf, 0x11, 0xd8, 0x59, 0x22, 0xf0, 0x11, 0x12, 0xa0,
	0x72, 0x6e, 0xea, 0xd3, 0x3c, 0xf4, 0x69, 0x56, 0x3a, 0xb4, 0xe6, 0x47, 0xbb, 0x1a, 0xd3, 0x63,
	0xb1, 0xc0, 0xb7, 0xbe, 0x0b, 0x37, 0x96, 0xc8, 0xe9, 0x15, 0x28, 0xf7, 0xd4, 0xb1, 0xcb, 0x5e,
	0x15, 0xe7, 0x47, 0x5a, 0x83, 0xea, 0x07, 0x99, 0x64, 0xca, 0x65, 0x2e, 0x8b, 0xa2, 0x78, 0x50,
	0xba, 0x4f, 0xf8, 0x2b, 0xb8, 0x3c, 0xbb, 0xa9, 0xbf, 0x3e, 0xe0, 0x36, 0x6c, 0xa0, 0x41, 0x99,
	0x1c, 0xc4, 0x27, 0x85, 0x5f, 0x45, 0xfc, 0x6e, 0xf0, 0x0c, 0x6a, 0x7f, 0x6c, 0x5e, 0x1d, 0x9a,
	0x34, 0xa2, 0x14, 0x2a, 0x27, 0x46, 0x2b, 0x4f, 0x8f, 0x3b, 0x4f, 0x31, 0x55, 0x9a, 0x61, 0xea,
	0x0e, 0x5c, 0xe8, 0xfb, 0x7f, 0x87, 0xe5, 0x06, 0x59, 0x0e, 0xd5, 0x2f, 0x59, 0xe7, 0x2d, 0xd4,
	0xf6, 0x75, 0x57, 0x59, 0x2c, 0x58, 0xd8, 0x4b, 0x8d, 0x46, 0xa5, 0x23, 0xba, 0x07, 0x9b, 0x53,
	0x88, 0xd0, 0x9b, 0x8b, 0xa0, 0x72, 0xfb, 0xad, 0xd7, 0x17, 0xf2, 0xe6, 0xf6, 0xc2, 0x83, 0xce,
	0x17, 0x02, 0x17, 0xa7, 0x2f, 0xf8, 0x5f, 0xc6, 0x34, 0x82, 0xad, 0x85, 0x4c, 0xd0, 0x5b, 0xab,
	0x89, 0x29, 0xbc, 0x6f, 0xff, 0x0b, 0x56, 0x3c, 0x78, 0x7c, 0x6f, 0x38, 0x62, 0xc1, 0xe9, 0x88,
	0x05, 0x67, 0x23, 0x46, 0x3e, 0xe6, 0x8c, 0x7c, 0xce, 0x19, 0xf9, 0x9a, 0x33, 0x32, 0xcc, 0x19,
	0xf9, 0x9e, 0x33, 0xf2, 0x23, 0x67, 0xc1, 0x59, 0xce, 0xc8, 0xa7, 0x31, 0x0b, 0x86, 0x63, 0x16,
	0x9c, 0x8e, 0x59, 0xf0, 0x6e, 0xcd, 0x99, 0xdf, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xad,
	0x3b, 0xc0, 0x38, 0x04, 0x00, 0x00,
}

func (this *CheckLimitsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CheckLimitsRequest)
	if !ok {
		that2, ok := that.(CheckLimitsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Tenant != that1.Tenant {
		return false
	}
	if len(this.Streams) != len(that1.Streams) {
		return false
	}
	for i := range this.Streams {
		if !this.Streams[i].Equal(that1.Streams[i]) {
			return false
		}
	}
	return true
}
func (this *CheckLimitsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CheckLimitsResponse)
	if !ok {
		that2, ok := that.(CheckLimitsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Results) != len(that1.Results) {
		return false
	}
	for i := range this.Results {
		if !this.Results[i].Equal(that1.Results[i]) {
			return false
		}
	}
	return true
}
func (this *CheckLimitsResult) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CheckLimitsResult)
	if !ok {
		that2, ok := that.(CheckLimitsResult)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.StreamHash != that1.StreamHash {
		return false
	}
	if this.Reason != that1.Reason {
		return false
	}
	return true
}
func (this *GetAssignedPartitionsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetAssignedPartitionsRequest)
	if !ok {
		that2, ok := that.(GetAssignedPartitionsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *GetAssignedPartitionsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetAssignedPartitionsResponse)
	if !ok {
		that2, ok := that.(GetAssignedPartitionsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.AssignedPartitions) != len(that1.AssignedPartitions) {
		return false
	}
	for i := range this.AssignedPartitions {
		if this.AssignedPartitions[i] != that1.AssignedPartitions[i] {
			return false
		}
	}
	return true
}
func (this *StreamMetadata) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StreamMetadata)
	if !ok {
		that2, ok := that.(StreamMetadata)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.StreamHash != that1.StreamHash {
		return false
	}
	if this.TotalSize != that1.TotalSize {
		return false
	}
	return true
}
func (this *StreamMetadataRecord) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StreamMetadataRecord)
	if !ok {
		that2, ok := that.(StreamMetadataRecord)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Zone != that1.Zone {
		return false
	}
	if this.Tenant != that1.Tenant {
		return false
	}
	if !this.Metadata.Equal(that1.Metadata) {
		return false
	}
	return true
}
func (this *CheckLimitsRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&proto.CheckLimitsRequest{")
	s = append(s, "Tenant: "+fmt.Sprintf("%#v", this.Tenant)+",\n")
	if this.Streams != nil {
		s = append(s, "Streams: "+fmt.Sprintf("%#v", this.Streams)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CheckLimitsResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&proto.CheckLimitsResponse{")
	if this.Results != nil {
		s = append(s, "Results: "+fmt.Sprintf("%#v", this.Results)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CheckLimitsResult) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&proto.CheckLimitsResult{")
	s = append(s, "StreamHash: "+fmt.Sprintf("%#v", this.StreamHash)+",\n")
	s = append(s, "Reason: "+fmt.Sprintf("%#v", this.Reason)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetAssignedPartitionsRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&proto.GetAssignedPartitionsRequest{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetAssignedPartitionsResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&proto.GetAssignedPartitionsResponse{")
	keysForAssignedPartitions := make([]int32, 0, len(this.AssignedPartitions))
	for k, _ := range this.AssignedPartitions {
		keysForAssignedPartitions = append(keysForAssignedPartitions, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForAssignedPartitions)
	mapStringForAssignedPartitions := "map[int32]int64{"
	for _, k := range keysForAssignedPartitions {
		mapStringForAssignedPartitions += fmt.Sprintf("%#v: %#v,", k, this.AssignedPartitions[k])
	}
	mapStringForAssignedPartitions += "}"
	if this.AssignedPartitions != nil {
		s = append(s, "AssignedPartitions: "+mapStringForAssignedPartitions+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *StreamMetadata) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&proto.StreamMetadata{")
	s = append(s, "StreamHash: "+fmt.Sprintf("%#v", this.StreamHash)+",\n")
	s = append(s, "TotalSize: "+fmt.Sprintf("%#v", this.TotalSize)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *StreamMetadataRecord) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&proto.StreamMetadataRecord{")
	s = append(s, "Zone: "+fmt.Sprintf("%#v", this.Zone)+",\n")
	s = append(s, "Tenant: "+fmt.Sprintf("%#v", this.Tenant)+",\n")
	if this.Metadata != nil {
		s = append(s, "Metadata: "+fmt.Sprintf("%#v", this.Metadata)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringLimits(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IngestLimitsFrontendClient is the client API for IngestLimitsFrontend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IngestLimitsFrontendClient interface {
	CheckLimits(ctx context.Context, in *CheckLimitsRequest, opts ...grpc.CallOption) (*CheckLimitsResponse, error)
}

type ingestLimitsFrontendClient struct {
	cc *grpc.ClientConn
}

func NewIngestLimitsFrontendClient(cc *grpc.ClientConn) IngestLimitsFrontendClient {
	return &ingestLimitsFrontendClient{cc}
}

func (c *ingestLimitsFrontendClient) CheckLimits(ctx context.Context, in *CheckLimitsRequest, opts ...grpc.CallOption) (*CheckLimitsResponse, error) {
	out := new(CheckLimitsResponse)
	err := c.cc.Invoke(ctx, "/proto.IngestLimitsFrontend/CheckLimits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngestLimitsFrontendServer is the server API for IngestLimitsFrontend service.
type IngestLimitsFrontendServer interface {
	CheckLimits(context.Context, *CheckLimitsRequest) (*CheckLimitsResponse, error)
}

// UnimplementedIngestLimitsFrontendServer can be embedded to have forward compatible implementations.
type UnimplementedIngestLimitsFrontendServer struct {
}

func (*UnimplementedIngestLimitsFrontendServer) CheckLimits(ctx context.Context, req *CheckLimitsRequest) (*CheckLimitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckLimits not implemented")
}

func RegisterIngestLimitsFrontendServer(s *grpc.Server, srv IngestLimitsFrontendServer) {
	s.RegisterService(&_IngestLimitsFrontend_serviceDesc, srv)
}

func _IngestLimitsFrontend_CheckLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestLimitsFrontendServer).CheckLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IngestLimitsFrontend/CheckLimits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestLimitsFrontendServer).CheckLimits(ctx, req.(*CheckLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IngestLimitsFrontend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IngestLimitsFrontend",
	HandlerType: (*IngestLimitsFrontendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckLimits",
			Handler:    _IngestLimitsFrontend_CheckLimits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/limits/proto/limits.proto",
}

// IngestLimitsClient is the client API for IngestLimits service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IngestLimitsClient interface {
	CheckLimits(ctx context.Context, in *CheckLimitsRequest, opts ...grpc.CallOption) (*CheckLimitsResponse, error)
	GetAssignedPartitions(ctx context.Context, in *GetAssignedPartitionsRequest, opts ...grpc.CallOption) (*GetAssignedPartitionsResponse, error)
}

type ingestLimitsClient struct {
	cc *grpc.ClientConn
}

func NewIngestLimitsClient(cc *grpc.ClientConn) IngestLimitsClient {
	return &ingestLimitsClient{cc}
}

func (c *ingestLimitsClient) CheckLimits(ctx context.Context, in *CheckLimitsRequest, opts ...grpc.CallOption) (*CheckLimitsResponse, error) {
	out := new(CheckLimitsResponse)
	err := c.cc.Invoke(ctx, "/proto.IngestLimits/CheckLimits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestLimitsClient) GetAssignedPartitions(ctx context.Context, in *GetAssignedPartitionsRequest, opts ...grpc.CallOption) (*GetAssignedPartitionsResponse, error) {
	out := new(GetAssignedPartitionsResponse)
	err := c.cc.Invoke(ctx, "/proto.IngestLimits/GetAssignedPartitions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngestLimitsServer is the server API for IngestLimits service.
type IngestLimitsServer interface {
	CheckLimits(context.Context, *CheckLimitsRequest) (*CheckLimitsResponse, error)
	GetAssignedPartitions(context.Context, *GetAssignedPartitionsRequest) (*GetAssignedPartitionsResponse, error)
}

// UnimplementedIngestLimitsServer can be embedded to have forward compatible implementations.
type UnimplementedIngestLimitsServer struct {
}

func (*UnimplementedIngestLimitsServer) CheckLimits(ctx context.Context, req *CheckLimitsRequest) (*CheckLimitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckLimits not implemented")
}
func (*UnimplementedIngestLimitsServer) GetAssignedPartitions(ctx context.Context, req *GetAssignedPartitionsRequest) (*GetAssignedPartitionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssignedPartitions not implemented")
}

func RegisterIngestLimitsServer(s *grpc.Server, srv IngestLimitsServer) {
	s.RegisterService(&_IngestLimits_serviceDesc, srv)
}

func _IngestLimits_CheckLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestLimitsServer).CheckLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IngestLimits/CheckLimits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestLimitsServer).CheckLimits(ctx, req.(*CheckLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestLimits_GetAssignedPartitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssignedPartitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestLimitsServer).GetAssignedPartitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IngestLimits/GetAssignedPartitions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestLimitsServer).GetAssignedPartitions(ctx, req.(*GetAssignedPartitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IngestLimits_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IngestLimits",
	HandlerType: (*IngestLimitsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckLimits",
			Handler:    _IngestLimits_CheckLimits_Handler,
		},
		{
			MethodName: "GetAssignedPartitions",
			Handler:    _IngestLimits_GetAssignedPartitions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/limits/proto/limits.proto",
}

func (m *CheckLimitsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckLimitsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CheckLimitsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Streams) > 0 {
		for iNdEx := len(m.Streams) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Streams[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLimits(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = encodeVarintLimits(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CheckLimitsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckLimitsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CheckLimitsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Results) > 0 {
		for iNdEx := len(m.Results) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Results[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLimits(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CheckLimitsResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckLimitsResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CheckLimitsResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reason != 0 {
		i = encodeVarintLimits(dAtA, i, uint64(m.Reason))
		i--
		dAtA[i] = 0x10
	}
	if m.StreamHash != 0 {
		i = encodeVarintLimits(dAtA, i, uint64(m.StreamHash))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetAssignedPartitionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAssignedPartitionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAssignedPartitionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetAssignedPartitionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAssignedPartitionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAssignedPartitionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AssignedPartitions) > 0 {
		for k := range m.AssignedPartitions {
			v := m.AssignedPartitions[k]
			baseI := i
			i = encodeVarintLimits(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i = encodeVarintLimits(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintLimits(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *StreamMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StreamMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalSize != 0 {
		i = encodeVarintLimits(dAtA, i, uint64(m.TotalSize))
		i--
		dAtA[i] = 0x10
	}
	if m.StreamHash != 0 {
		i = encodeVarintLimits(dAtA, i, uint64(m.StreamHash))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StreamMetadataRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StreamMetadataRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StreamMetadataRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLimits(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = encodeVarintLimits(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Zone) > 0 {
		i -= len(m.Zone)
		copy(dAtA[i:], m.Zone)
		i = encodeVarintLimits(dAtA, i, uint64(len(m.Zone)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLimits(dAtA []byte, offset int, v uint64) int {
	offset -= sovLimits(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CheckLimitsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Tenant)
	if l > 0 {
		n += 1 + l + sovLimits(uint64(l))
	}
	if len(m.Streams) > 0 {
		for _, e := range m.Streams {
			l = e.Size()
			n += 1 + l + sovLimits(uint64(l))
		}
	}
	return n
}

func (m *CheckLimitsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Results) > 0 {
		for _, e := range m.Results {
			l = e.Size()
			n += 1 + l + sovLimits(uint64(l))
		}
	}
	return n
}

func (m *CheckLimitsResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StreamHash != 0 {
		n += 1 + sovLimits(uint64(m.StreamHash))
	}
	if m.Reason != 0 {
		n += 1 + sovLimits(uint64(m.Reason))
	}
	return n
}

func (m *GetAssignedPartitionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetAssignedPartitionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AssignedPartitions) > 0 {
		for k, v := range m.AssignedPartitions {
			_ = k
			_ = v
			mapEntrySize := 1 + sovLimits(uint64(k)) + 1 + sovLimits(uint64(v))
			n += mapEntrySize + 1 + sovLimits(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *StreamMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StreamHash != 0 {
		n += 1 + sovLimits(uint64(m.StreamHash))
	}
	if m.TotalSize != 0 {
		n += 1 + sovLimits(uint64(m.TotalSize))
	}
	return n
}

func (m *StreamMetadataRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Zone)
	if l > 0 {
		n += 1 + l + sovLimits(uint64(l))
	}
	l = len(m.Tenant)
	if l > 0 {
		n += 1 + l + sovLimits(uint64(l))
	}
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovLimits(uint64(l))
	}
	return n
}

func sovLimits(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLimits(x uint64) (n int) {
	return sovLimits(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CheckLimitsRequest) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForStreams := "[]*StreamMetadata{"
	for _, f := range this.Streams {
		repeatedStringForStreams += strings.Replace(f.String(), "StreamMetadata", "StreamMetadata", 1) + ","
	}
	repeatedStringForStreams += "}"
	s := strings.Join([]string{`&CheckLimitsRequest{`,
		`Tenant:` + fmt.Sprintf("%v", this.Tenant) + `,`,
		`Streams:` + repeatedStringForStreams + `,`,
		`}`,
	}, "")
	return s
}
func (this *CheckLimitsResponse) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForResults := "[]*CheckLimitsResult{"
	for _, f := range this.Results {
		repeatedStringForResults += strings.Replace(f.String(), "CheckLimitsResult", "CheckLimitsResult", 1) + ","
	}
	repeatedStringForResults += "}"
	s := strings.Join([]string{`&CheckLimitsResponse{`,
		`Results:` + repeatedStringForResults + `,`,
		`}`,
	}, "")
	return s
}
func (this *CheckLimitsResult) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CheckLimitsResult{`,
		`StreamHash:` + fmt.Sprintf("%v", this.StreamHash) + `,`,
		`Reason:` + fmt.Sprintf("%v", this.Reason) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetAssignedPartitionsRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetAssignedPartitionsRequest{`,
		`}`,
	}, "")
	return s
}
func (this *GetAssignedPartitionsResponse) String() string {
	if this == nil {
		return "nil"
	}
	keysForAssignedPartitions := make([]int32, 0, len(this.AssignedPartitions))
	for k, _ := range this.AssignedPartitions {
		keysForAssignedPartitions = append(keysForAssignedPartitions, k)
	}
	github_com_gogo_protobuf_sortkeys.Int32s(keysForAssignedPartitions)
	mapStringForAssignedPartitions := "map[int32]int64{"
	for _, k := range keysForAssignedPartitions {
		mapStringForAssignedPartitions += fmt.Sprintf("%v: %v,", k, this.AssignedPartitions[k])
	}
	mapStringForAssignedPartitions += "}"
	s := strings.Join([]string{`&GetAssignedPartitionsResponse{`,
		`AssignedPartitions:` + mapStringForAssignedPartitions + `,`,
		`}`,
	}, "")
	return s
}
func (this *StreamMetadata) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StreamMetadata{`,
		`StreamHash:` + fmt.Sprintf("%v", this.StreamHash) + `,`,
		`TotalSize:` + fmt.Sprintf("%v", this.TotalSize) + `,`,
		`}`,
	}, "")
	return s
}
func (this *StreamMetadataRecord) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StreamMetadataRecord{`,
		`Zone:` + fmt.Sprintf("%v", this.Zone) + `,`,
		`Tenant:` + fmt.Sprintf("%v", this.Tenant) + `,`,
		`Metadata:` + strings.Replace(this.Metadata.String(), "StreamMetadata", "StreamMetadata", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringLimits(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CheckLimitsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLimits
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckLimitsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckLimitsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimits
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLimits
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLimits
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Streams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimits
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLimits
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLimits
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Streams = append(m.Streams, &StreamMetadata{})
			if err := m.Streams[len(m.Streams)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLimits(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CheckLimitsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLimits
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckLimitsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckLimitsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Results", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimits
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLimits
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLimits
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Results = append(m.Results, &CheckLimitsResult{})
			if err := m.Results[len(m.Results)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLimits(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CheckLimitsResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLimits
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckLimitsResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckLimitsResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamHash", wireType)
			}
			m.StreamHash = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimits
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StreamHash |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			m.Reason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimits
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reason |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLimits(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAssignedPartitionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLimits
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAssignedPartitionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAssignedPartitionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipLimits(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAssignedPartitionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLimits
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAssignedPartitionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAssignedPartitionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssignedPartitions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimits
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLimits
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLimits
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AssignedPartitions == nil {
				m.AssignedPartitions = make(map[int32]int64)
			}
			var mapkey int32
			var mapvalue int64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLimits
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLimits
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLimits
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipLimits(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthLimits
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.AssignedPartitions[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLimits(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StreamMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLimits
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StreamHash", wireType)
			}
			m.StreamHash = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimits
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StreamHash |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSize", wireType)
			}
			m.TotalSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimits
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLimits(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StreamMetadataRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLimits
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StreamMetadataRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StreamMetadataRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Zone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimits
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLimits
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLimits
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Zone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimits
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLimits
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLimits
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLimits
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLimits
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLimits
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &StreamMetadata{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLimits(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLimits
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLimits(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLimits
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLimits
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLimits
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLimits
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthLimits
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowLimits
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipLimits(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthLimits
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthLimits = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLimits   = fmt.Errorf("proto: integer overflow")
)
